CREATE DATABASE QSELECAO_BINARIOS;

USE QSELECAO_BINARIOS;


SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FW_CONTEUDOS_BINARIOS](
	[TIPO_CONTEUDO_BINARIO] [tinyint] NOT NULL,
	[COD_CONTEUDO_BINARIO] [int] NOT NULL,
	[NOME_ARQUIVO] [varchar](100) NOT NULL,
	[CONTEUDO_BINARIO] [image] NOT NULL,
	[COMPACTADO] [tinyint] NOT NULL,
 CONSTRAINT [XPKFW_CONTEUDOS_BINARIOS] PRIMARY KEY CLUSTERED 
(
	[TIPO_CONTEUDO_BINARIO] ASC,
	[COD_CONTEUDO_BINARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FW_CONTEUDOS_BINARIOS] ADD  CONSTRAINT [Set_To_Zero114]  DEFAULT (0) FOR [COMPACTADO]
GO

